version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/server/
    command: uvicorn src.main:app --proxy-headers --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
